### ISSUE TITLE
missing files: skater/south_inf_q20.ary

### ISSUE THREAD

**Issue by sjsrey** [pysal/region#19]
When installing via
```
pip install https://github.com/pysal/region/archive/master.zip
```
into a  prebuilt and activated conda environment for [osnap](https://github.com/spatialucr/osnap/issues/8)
I  hit
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/serge/anaconda3/envs/osnap-region/lib/python3.6/site-packages/region/skater/south_inf_q20.ary'
```
looks like the file doesn't come along for the installation ride?

**Comment by ljwolf** [comment]
sorry, probably needs to be added to MANIFEST.in.

**Comment by ljwolf** [comment]
that should only be required for testing, though... not sure why you're hitting it in installation?

**Comment by sjsrey** [comment]
I think because: https://github.com/pysal/region/blob/master/region/skater/__init__.py#L2

**Comment by knaaptime** [comment]
fwiw, i also get a `AttributeError: 'Series' object has no attribute 'reshape'` when trying to *use* skater, but i can raise that elsewhere

**Comment by ljwolf** [comment]
Yes, @knaaptime replication code would help me address that. 
On this, I can submit a PR removing the read statement in `test_skater`. that's not supposed to be there.

**Comment by ljwolf** [comment]
> fwiw, i also get a `AttributeError: 'Series' object has no attribute 'reshape'` when trying to _use_ skater, but i can raise that elsewhere

Thinking about this error, I bet it's because I'm not using `asarray` on the input, and something in scipy/sklearn is mad that the input is a Pandas series, not an array. 

I can PR that.,
