### ISSUE TITLE
version?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/region#29]
Currently in [`setup.py`](https://github.com/pysal/region/blob/master/setup.py#L12) the version is listed as `0.1.5`. Also, within [`region.skater.__version__`](https://github.com/pysal/region/blob/master/region/skater/__version__.py) the version is listed as `1.0.0`.

Are these version mutually exclusive of one another or should one take precedence over another?

@ljwolf

**Comment by ljwolf** [comment]
That's because ljwolf/regionskate was/is a separate package. That version was just the version when we copied the source tree into region.
