### ISSUE TITLE
Fix or ignore failure due to EOL?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/region#43]
Should the current [Travis CI failure](https://travis-ci.org/pysal/region/builds/626012708?utm_source=github_status&utm_medium=notification) be ignored or fixed due the End-of-Life status fo `region`? FWIW, the travis failures are due to the new `libpysal.examples` schema.

@sjsrey

**Comment by knaaptime** [comment]
i think we leave it for now and focus attention on spopt

**Comment by knaaptime** [comment]
resolved by #44
